import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { motion } from 'framer-motion'
import Circle from '@/components/Circle'
import FadeInOut from '@/components/FadeInOut'
import Project from '@/components/Project'
// Fonts
import { Open_Sans, Crimson_Text, Inter } from 'next/font/google'
const opensans = Open_Sans({ subsets: ['latin'] })
const crimsonText = Crimson_Text({subsets: ['latin'],weight: ['700']})
const inter = Inter({ subsets: ['latin'] })
import styles from '@/styles/Home.module.css'


const projects = [
  {
    title: 'Resonance Domes',
    challenge: `Design a gathering space in harmony with the earth.`,
    solution: (`Sourced a building technique using hempcrete, basalt rock mesh, and ceramic.
      Our first dome is set for construction at trueHOME Hudson, NY ~ Summer 2023`),
    link: 'https://resonance-domes.vercel.app',
    iframe: true,
    landscape: true,
    images: [
      {
        src: '/chrysanthemum_full.jpg',
        alt: 'Chrysanthemum visual'
      },
       {
        src: '/resonance_domes_logo.svg',
        alt: 'Resonance Domes logo',
        objectFit: 'contain'
      }
    ],
  },
  {
    title: 'Chrysanthemum',
    challenge: `Make my inner visions externally visible.`,
    solution: `Teach myself the tools of generative algorithmic art.`,
    link: 'https://chrysanthemum.app',
    iframe: true,
    images: [
      {
        src: '/chrysanthemum_samples.png',
        alt: 'Chrysanthemum samples'
      }
    ]
  },
  {
    title: 'InPhiKnit',
    challenge: `Collaborate with my partner to illuminate the subtle body through art.`,
    solution: `Discover textures that feel like etheric weavings.`,
    link: 'https://in-phi-knit.vercel.app',
    iframe: true,
    images: [
      {
        src: '/chrysanthemum_samples.png',
        alt: 'Chrysanthemum samples'
      }
    ]
  },
]


export default function Home() {
  return (
    <>
      <Head>
        <title>Daniel Friedman Space</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/drop_white.svg" />
      </Head>

      <main className={styles.main}>
        <div className={styles.description}>
          <div className={styles.nav + " relative contents w-full h-full justify-start items-start pointer-events-none"}>
            <div className="w-20 h-20 p-4">
              <Circle layoutRoot />
            </div>
          </div>
          <motion.span
            layout="position"
            layoutRoot
            layoutId={'description-text'}
            transition={{duration: 1}}
            >
            <FadeInOut>
              Portfolio / Artist
            </FadeInOut>

          </motion.span>
        </div>

        <motion.div
          className="flex flex-col text-center justify-center p-4 min-h-[80vh] sm:min-h-[60vh]"
          initial={{opacity: 0, y: -20}}
          animate={{opacity: 1, y: 0}}
          exit={{opacity: 0}}
          transition={{duration: 2}}
        >
          <h1 className={crimsonText.className + " text-3xl"}
            style={{
              // backgroundImage: 'linear-gradient(to left, #ead4ef, #a5a1ef, #97b2ef, #b8ebbf, #e9eb89, #edcc9c, #f3bcb4)',

              // backgroundImage: 'linear-gradient(to left, #d96ebd, #756ee7, #437dff, #93ffa1, #fcff7a, #ffbc5b, #ff4e4e)',
              // backgroundImage: 'linear-gradient(to left, #440032, #1f0048, #001034, #002605, #3d3e00, #3e2500, #360000)',
              // backgroundImage: 'linear-gradient(to left, #fbebff, #d8ceff, #c9d9ff, #ddffe2, #feffcd, #ffeacb, #ffdcd7)',

                // '-webkit-background-clip': 'text',
                // '-webkit-text-fill-color': 'transparent'
            }}>
            Hi, thanks for being here :)
            <br/><br/><br/>I love to create art that's both
            <br/>beautiful and useful
            <br/><br/><br/>Please explore a few<br/>examples below...
          </h1>
        </motion.div>

        <div className={styles.glow + ' container pt-12'}>
          {
            projects.map((project, i) =>
              (<Project project={project} offset={i} key={i} />)
            )
          }
        </div>
        <div className="pb-16 text-center">
          <h1 className={crimsonText.className + " text-3xl"}>
            Contact me here to collaborate together
          </h1>
          <p className={inter.className}>
            dan.friedma@gmail.com
          </p>
        </div>

      </main>
    </>
  )
}
